Lp 36 fe refactor
meninas-em-ti/library-system pull request #14
Opened 2023-04-04 19:32 UTC by elainegui

LP-36 
**Click on the login button at the home page

* Add Thymeleaf tags

* Add Cypress structure

2023-04-04 20:04 UTC, brunaellen requested changes
As we discussed. You could remove this file as the login.hml file is the correct one to use for the login page.

2023-04-04 20:04 UTC, brunaellen commented on src/main/resources/templates/login_old.html
As we discussed. You could remove this file as the `login.hml` file is the correct one to use for the login page.

2023-04-18 18:28 UTC, RaquelOliveira commented on src/main/resources/templates/base.html
>          <button type="button" class="btn btn-primary">Sign-up</button>
It would be good to put all the buttons inside of the form to not break the page

2023-04-18 18:31 UTC, RaquelOliveira commented on test-cypress/cypress/e2e/1-getting-started/login.cy.js
> +    // it('displays two todo items by default', () => {
are we going to use this commented code? Otherwise it would be good to remove it.

2023-04-18 18:41 UTC, joycesilvamartins commented on .gitignore
> +!**/test-cypress/node_modules/
It would be good to add the steps to run Cypress in our Readme file

2023-04-18 18:41 UTC, joycesilvamartins commented on src/main/resources/templates/login_old.html
> +    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
As we discussed, we can remove this file.

2023-04-18 18:41 UTC, joycesilvamartins commented on test-cypress/cypress/e2e/2-advanced-examples/actions.cy.js
> +      .type('{del}{selectall}{backspace}')
As we discussed, we can remove the 2-advanced-examples directory.

2023-04-18 18:41 UTC, joycesilvamartins commented on src/main/resources/templates/login.html
> +                        <input class="form-input" type="text"  name="password" id="password"  />
Change the input type to the password (to mask the password)

2023-04-18 18:41 UTC, joycesilvamartins commented on test-cypress/cypress/e2e/1-getting-started/login-test.cy.js
> +        cy.get('#password').type('123456')
Change the username (Admin), password (Admin@123")

2023-04-18 18:41 UTC, joycesilvamartins commented on test-cypress/cypress/e2e/2-advanced-examples/actions.cy.js
Maybe we can remove this folder as is just examples.

2023-04-18 18:41 UTC, joycesilvamartins commented on test-cypress/cypress/fixtures/example.json
Maybe we can remove this file as just an example.

2023-04-18 19:45 UTC, elainegui commented on .gitignore
> +!**/test-cypress/node_modules/
we decided to leave this to the next sprint

2023-04-18 20:02 UTC, merged